### ISSUE TITLE
Consider making this open-source

### ISSUE THREAD

**Issue by Polyrhythm** [Imgur/imgur.js#6]
It's good enough to be out in the wild. We can add notices about it not being super useful yet, but I don't see a reason to lock this down.

Benefits:
- possible suggestions/collaboration
- less error-prone when pulling in from `package.json` (NPM is currently complaining at me)
- more visibility for the Imgur engineering team from open source community at large

@magicgrl111 @briankassouf @ecto @jessthepeterson

**Comment by btipling** [comment]
It's already open source?
